apiVersion: apps/v1
kind: Deployment
metadata:
  name: jatin
  labels:
    app: django-blog

spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-blog
      
  template:
    metadata:
      labels:
        app: django-blog
        
    spec:
      containers:
      - name: jatin
        image: jatinchawla/jatin-img:1.1
        ports:
        - containerPort: 8000
